[flags]
    tree = true
    battery = true
    celsius = true
    hide_avg_cpu = true
    mem_as_value = true
    left_legend = false
    rate = 500
[[row]]
    ratio = 1
    [[row.child]]
        type = "memory"
    [[row.child]]
        type = "cpu"
[[row]]
    ratio = 2
    [[row.child]]
        ratio = 4
        type = "process"
    [[row.child]]
        ratio = 3
        [[row.child.child]]
            ratio = 2
            type = "network"
        [[row.child.child]]
            ratio = 2
            type = "battery"
        [[row.child.child]]
            ratio = 1
            type = "disk"
