[flags]
tree = true
[[row]]
  [[row.child]]
  type="cpu"
[[row]]
    ratio=2
    [[row.child]]
      ratio=4
      type="process"
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="mem"
      [[row.child.child]]
        type="disk"
