return {
    "EdenEast/nightfox.nvim",
    event = "VimEnter",
    config = function()
        local colors = {
            rosewater = "#ff8389",
            flamingo = "#ff8389",
            red = "#ff8389",
            maroon = "#ff8389",
            pink = "#ff7eb6",
            mauve = "#be95ff",
            peach = "#d44a1c",
            yellow = "#ab8600",
            green = "#08bdba",
            teal = "#33b1ff",
            sky = "#33b1ff",
            sapphire = "#33b1ff",
            blue = "#78a9ff",
            lavender = "#78a9ff",
            text = "#ffffff",
            subtext1 = "#f4f4f4",
            subtext0 = "#e0e0e0",
            overlay2 = "#adadad",
            overlay1 = "#949494",
            overlay0 = "#7a7a7a",
            surface2 = "#4f4f4f",
            surface1 = "#383838",
            surface0 = "#2e2e2e",
            base = "#161616",
            mantle = "#0d0d0d",
            crust = "#000000",
        }
        require("nightfox").setup({
            options = {
                terminal_colors = true,
                transparent = true,
                styles = {
                },
            },
            groups = {
                all = {
                    GitSignsChange = { fg = colors.peach },
                    LineNr = { fg = colors.surface1 },
                    IndentBlanklineChar = { fg = colors.surface0 },
                    IndentBlanklineContextChar = { fg = colors.surface2 },
                    NeoTreeNormal = { bg = colors.mantle },
                    NeoTreeRootName = { fg = colors.blue },
                    NeoTreeNormalNC = { bg = colors.mantle },
                    NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
                    NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
                    NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
                    NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
                    NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
                    NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
                    NeoTreeGitConflict = { fg = colors.red },
                    NeoTreeGitDeleted = { fg = colors.red },
                    NeoTreeGitIgnored = { fg = colors.overlay0 },
                    NeoTreeGitModified = { fg = colors.peach },
                    NeoTreeGitUnstaged = { fg = colors.red },
                    NeoTreeGitUntracked = { fg = colors.blue },
                    NeoTreeGitStaged = { fg = colors.green },
                },
            },
        })
        vim.cmd [[colorscheme carbonfox]]
    end,
}
