format = '$python$directory$all$character'
command_timeout = 1000
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = '[ ](bold white)'
error_symbol = '[ ](bold white)'

[directory]
style = 'bold cyan'
truncation_length = 1
truncation_symbol = '~/'
format = '[$path ]($style)'

[git_branch]
style = 'bold red'
format = '[$branch ]($style)'

[git_status]
disabled = true

[python]
python_binary = 'python3'
style = 'bold yellow'
format = '[(\($virtualenv\)) ]($style)'
detect_extensions = []
detect_files = []

[aws]
disabled = true
[azure]
disabled = true
[battery]
disabled = true
[crystal]
disabled = true
[daml]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[gcloud]
disabled = true
[helm]
disabled = true
[kubernetes]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[terraform]
disabled = true
[rlang]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[package]
disabled = true
[time]
disabled = true
[swift]
disabled = true
[vagrant]
disabled = true
[vcsh]
disabled = true
[zig]
disabled = true
